/** Initial product catalog (matches frontend sample products). */
module.exports = [
  {
    name: 'Multi Grain Flour',
    price: 2800,
    description:
      'A nutritious blend of multiple grains for balanced health. Perfect for health-conscious families.',
    category: 'Health',
    image: '/images/Products/multigrain.png',
    weights: ['10kg', '20kg', '30kg', '40kg'],
    featured: true,
    inStock: true,
    rating: 4.9,
    reviews: 124,
  },
  {
    name: 'Regular Flour',
    price: 1800,
    description:
      'Everyday fine flour for soft and fluffy rotis. The staple choice for every Pakistani home.',
    category: 'Whole Wheat',
    image: '/images/Products/regular.png',
    weights: ['10kg', '20kg', '30kg', '40kg'],
    featured: false,
    inStock: true,
    rating: 4.7,
    reviews: 203,
  },
  {
    name: 'White Flour',
    price: 2000,
    description: 'Refined white flour ideal for pastries, cakes and baking. Silky smooth texture guaranteed.',
    category: 'Refined',
    image: '/images/Products/white.png',
    weights: ['10kg', '20kg', '30kg', '40kg'],
    featured: false,
    inStock: true,
    rating: 4.5,
    reviews: 89,
  },
  {
    name: 'Whole Wheat Flour',
    price: 2200,
    description: 'Made from whole grains for maximum nutrition. Stone-ground to preserve natural goodness.',
    category: 'Whole Wheat',
    image: '/images/Products/wholegrain.png',
    weights: ['10kg', '20kg', '30kg', '40kg'],
    featured: true,
    inStock: true,
    rating: 4.8,
    reviews: 156,
  },
  {
    name: 'Fine Flour (Pratha)',
    price: 2400,
    description: 'Extra fine texture, perfect for parathas and naans. Makes the softest layered parathas.',
    category: 'Specialty',
    image: '/images/Products/fine.png',
    weights: ['10kg', '20kg', '30kg', '40kg'],
    featured: false,
    inStock: true,
    rating: 4.6,
    reviews: 78,
  },
  {
    name: 'Maida',
    price: 2100,
    description: 'Refined wheat flour for bakery and sweets. Essential for samosas, jalebis and baked goods.',
    category: 'Refined',
    image: '/images/Products/maida.png',
    weights: ['10kg', '20kg', '30kg', '40kg'],
    featured: false,
    inStock: true,
    rating: 4.5,
    reviews: 92,
  },
  {
    name: 'Barley',
    price: 1600,
    description: 'Rich in fiber and ideal for health-conscious diets. Traditional grain with modern health benefits.',
    category: 'Health',
    image: '/images/Products/barley.png',
    weights: ['10kg', '20kg', '30kg'],
    featured: false,
    inStock: true,
    rating: 4.4,
    reviews: 45,
  },
  {
    name: 'Bran (Choker)',
    price: 800,
    description: 'High in fiber, perfect for digestion and diet plans. Natural wheat bran for healthy living.',
    category: 'Health',
    image: '/images/Products/bran.png',
    weights: ['10kg', '20kg', '30kg'],
    featured: false,
    inStock: true,
    rating: 4.3,
    reviews: 38,
  },
  {
    name: 'Suji',
    price: 1500,
    description: 'Coarse wheat flour perfect for halwa, upma and traditional Pakistani desserts.',
    category: 'Specialty',
    image: '/images/Products/suji.png',
    weights: ['10kg', '20kg', '30kg'],
    featured: false,
    inStock: true,
    rating: 4.6,
    reviews: 67,
  },
  {
    name: 'Oats Flour',
    price: 3200,
    description: 'Gluten-free, heart-friendly flour from premium oats. Perfect for healthy breakfast options.',
    category: 'Health',
    image: '/images/Products/regular.png',
    weights: ['10kg', '20kg', '30kg'],
    featured: false,
    inStock: true,
    rating: 4.7,
    reviews: 52,
  },
];
